config/routes.rb
Rails.application.routes.draw do
  
  resources :lists
  resources :user
  resources :classrooms
  resources :materials do
    resources :favorites
    resources :comments
  end
  devise_for :users 

  root 'welcome#index'
  get 'bye' => "welcome#bye"
  delete 'materials/:material_id/favorites' => "favorites#destroy"
  post 'materials/:material_id/comments' => "comments#create"
  get 'list/:material_id/:list_id' => 'lists#materialToList'

end

app/models/classroom.rb
class Classroom
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
  field :public, type: Mongoid::Boolean
  field :password, type: String
  field :college, type: String
  has_and_belongs_to_many :users
end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps
  field :body, type: String
  field :user_id, type: String
  embedded_in :material, :inverse_of => :comments
end

app/models/favorite.rb
class Favorite
  include Mongoid::Document
  include Mongoid::Timestamps
  belongs_to :material
  belongs_to :user
end

app/models/list.rb
class List
	include Mongoid::Document
	include Mongoid::Timestamps
	belongs_to :user
	field :name, type: String
	field :description, type: String
	field :public, type: Mongoid::Boolean
	field :materials, type: Array, default: []
end

app/models/material.rb
class Material
  include Mongoid::Document
  include Mongoid::Paperclip
  include Mongoid::Timestamps

  has_mongoid_attached_file :file
  do_not_validate_attachment_file_type :file
  field :name, type: String
  field :description, type: String
  field :format, type: String
  field :uploadDate, type: Date
  field :type, type: String
  field :authors, type: String
  field :searchable, type: Boolean
  field :tags, type: String
  field :schools, type: String
  field :subject, type: String
  field :updateDate, type: Date
  field :file_type, type: String

  #Youtube fields
  field :youtube_id, type: String
  field :video_duration, type: Integer
  field :thumbnail_url, type: String
  field :youtubeChannel_id, type: String
  field :youtubeChannel_avatar_url, type: String

  #Relations
  belongs_to :user
  embeds_many :comments
  has_many :favorites
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paperclip

  
  has_and_belongs_to_many :classrooms
  has_many :materials
  has_many :lists
  has_many :favorites

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  # Extra Info
    has_mongoid_attached_file :avatar

  ## Database authenticatable
  field :username,           type: String
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/models/video.rb
class Video
  include Mongoid::Document
  field :name, type: String
  field :description, type: String
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@comment = Material.find(params[:material_id]).comments.new()
		@comment.body = params[:body]
		@comment.user_id = current_user.id
		respond_to do |format|
        if @comment.save
          format.html { redirect_to material_path(params[:material_id]), notice: 'Comment was successfully created.' }
          
        else
          format.html { render material_path(params[:material_id]) }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end  
	end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	before_action :authenticate_user!
	def create
		
		#params --> :material_id
		@favorite = Favorite.new
	    @favorite.user_id = current_user.id
	    @favorite.material_id = params[:material_id]
	    #Is ajax?
	    if request.env["HTTP_X_REQUESTED_WITH"] == "XMLHttpRequest"
			#Hasn't this user favorited this material? 
			if !alreadyInFavs?(params[:material_id])
				if @favorite.save
			        render json: {}, status: :ok
			    else
			    	render json: @favorite.errors, status: :unprocessable_entity
			    end	
			else
				render json: {}, status: :conflict
			end
	      
		end
	end
	def destroy
		@favorite = Favorite.where({user_id: current_user.id}).first
		@favorite.destroy
		render json: {}, status: :ok
	end

	private
	
	def alreadyInFavs?(material_id)
		if Favorite.and({ user_id: current_user.id }, { material_id: params[:material_id] }).count >= 1
			return true
		else
			return false 
		end
	end


end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end
  def materialToList
    materialId = params[:material_id]
    listId = params[:list_id]
    if current_user.lists.where(id: listId).exists?
      @list = List.find(listId)
      if @list.materials.include?(materialId)
        @list.materials.delete(materialId)
        if @list.save
          render json: {}, status: :ok
        else
          render json: {}, status: :conflict
        end
      else
        if @list.push(materials: materialId)
          render json: {}, status: :ok
        else
          render json: {}, status: :conflict
        end
      end
    else
      render json: {}, status: :conflict
    end
  end
  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)
    @list.user_id = current_user.id

    respond_to do |format|
      if @list.save
        format.json { render :json => {:name => @list.name, :description => @list.description, :id => @list.id.to_s}, status: :created }
      else
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :description, :public)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	before_action :authenticate_user!
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/aplication/_no_user.html.erb
<div class="sesion">
	<div class="login">
		<%= link_to "Iniciar Sesión", new_user_session_path, class:"logintext" %>
	</div>
	<div class="signup">
		<%= link_to "Regístrate", new_user_registration_path, class:"signuptext" %>
	</div>
</div>

app/views/aplication/_notice.html.erb
<% if notice %>
	<div class="notice_shadow">
		<div class="notice">
			
			<div class="notice_msg">
			<%= notice %>
			<div class="close_notice icon remove"></div>
			</div>
			
		</div>
	</div>
	<script type="text/javascript">
	$(document).ready(function(){
		$(".close_notice").on("click", function(){
			$(".notice_shadow").addClass("invisible");
		})
	})
	</script>

<% end %>

app/views/aplication/_user_buttons.html.erb
<%= javascript_include_tag 'clickOutside' %>
<div class="panel">
	<%= link_to destroy_user_session_path, method: :delete,class: "signout"  do %>
		<div class="panelButton icon signout"></div>
	<% end %>

	<div class="fav panelButton icon angle-down">
		
		<div class="invisible user_menu">
		<div class="triangulo_sup"></div>
			<ul>
				<li>Aulas</li>
				<li>Listas</li>
				<li>Favoritos</li>
				<li>Mis Materiales</li>
				<br>
				<%= link_to destroy_user_session_path, method: :delete do %>
					<li> Cerrar Sesión </li>
				<% end %>
			</ul>
		</div>

	</div>
	<div class="panelButton username">
		<%= link_to user_index_path do %>
			<%= current_user.username %>
			<%= image_tag(current_user.avatar.url, class: "header_avatar") %>		
		<% end %>
	</div>
		

</div>
<script type="text/javascript">
	$(document).ready(function  () {
		$(".fav.angle-down").on("click", function(){
			if (!$(".fav.panelButton").hasClass("active_menu")) {
				setTimeout(function(){
					$(".user_menu").removeClass("invisible");
					$(".user_menu").addClass("visible_menu");
					$(".fav.angle-down").addClass("active_menu");
				},1)
			};
		});
		
		$(".user_menu").bind( 'clickoutside', function(event){
			if ($(".fav.panelButton").hasClass("active_menu")) {
				$(".user_menu").addClass("invisible");
				$(".user_menu").removeClass("visible_menu");
				$(".fav.angle-down").removeClass("active_menu");
			};
		});
	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>AppName</title>
	<link href="https://fonts.googleapis.com/css?family=Courgette" rel="stylesheet" type="text/css">
	<link href='https://fonts.googleapis.com/css?family=Roboto:400,400italic,500,300,300italic,500italic,700,700italic,900,100italic,100,900italic' rel='stylesheet' type='text/css'>
	<%= stylesheet_link_tag 'application'%>
	<%= javascript_include_tag 'application' %>
	<%= yield :head %>
</head>
<body>
<%= render '/aplication/notice.html.erb' %>

	<header class="header">
		<div class="logo"><%= link_to "Logo", root_path%></div>
		<div class="asignaturas">Asignaturas</div>
		<div class="asignaturas">Cursos</div>
		<div class="asignaturas">Top</div>
			
		<% if !user_signed_in? %>
			<%= render '/aplication/no_user.html.erb' %>
		<% else%>
			<%= render '/aplication/user_buttons.html.erb' %>
		<% end %>

		<%= link_to new_material_path, class: "uploadMaterial" do %>
			<div class="upploadMaterial">¡Publicar!</div>
		<% end %>

	</header>
<div class="webpage">
	<%= yield %>


	<div id="footer">
		Contacto | Sobre appName | ¡Ayúdanos! | Política y Privacidad
	</div>
</div>
</body>
</html>