config/routes.rb
Rails.application.routes.draw do
  
  resources :lists
  resources :user
  resources :classrooms
  resources :materials do
    resources :favorites
    resources :comments
  end
  devise_for :users 

  root 'welcome#index'
  get 'bye' => "welcome#bye"
  delete 'materials/:material_id/favorites' => "favorites#destroy"
  post 'materials/:material_id/comments' => "comments#create"
  get 'list/:material_id/:list_id' => 'lists#materialToList'

end

app/models/material.rb
class Material
  include Mongoid::Document
  include Mongoid::Paperclip
  include Mongoid::Timestamps

  has_mongoid_attached_file :file
  do_not_validate_attachment_file_type :file
  field :name, type: String
  field :description, type: String
  field :format, type: String
  field :uploadDate, type: Date
  field :type, type: String
  field :authors, type: String
  field :searchable, type: Boolean
  field :tags, type: String
  field :schools, type: String
  field :subject, type: String
  field :updateDate, type: Date
  field :file_type, type: String

  #Youtube fields
  field :youtube_id, type: String
  field :video_duration, type: Integer
  field :thumbnail_url, type: String
  field :youtubeChannel_id, type: String
  field :youtubeChannel_avatar_url, type: String

  #Relations
  belongs_to :user
  embeds_many :comments
  has_many :favorites
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_material, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:index, :show]
  # GET /materials
 
  # GET /materials.json
  def index

     #favorites of a user Material.where(:'favorites.user_id' => current_user.id)
     @subjects = ["Matematicas" , "Biologia", "Quimica", "Fisica"]
     if request.query_parameters
        query = {}
        request.query_parameters.each do  |key,value|
          if key != "utf8" && key != "commit" && value != "" && key != "search"
            query[key] = value
          end
          
          if key == "search" && value != ""
            valueSplitted = value.split(" ")
            regepxString = String
            valueSplitted.each_with_index do  |word , index|
              regepxString = "(?=.*" + word + ")"

              if index == valueSplitted.length - 1
                regepxString += ".*"
              end
            end            
            regexp = Regexp.new(regepxString, true) 
            query["name"] = regexp 
          end
        end
        query[:searchable] = true
        @materials = Material.where(query)
     else
        @materials = Material.where(:searchable => true)
     end
  end

  # GET /materials/1
  # GET /materials/1.json
  def show
    if @material.format == "video"
      @iframe = %Q'<iframe id="player" src="http://www.youtube.com/embed/#{@material.youtube_id}?&rel=0&theme=light&showinfo=0&color=white" frameborder="0" allowfullscreen></iframe>'.html_safe
      render 'show_video'
    elsif @material.file_type == "pdf"
      render 'show_pdf'
    elsif @material.file_type == "uploaded_video"
      render 'show_uploaded_video'
    elsif @material.file_type == 'image'
      render 'show_image'
    else
      render 'show'
    end
  end

  # GET /materials/new
  def new
    
    @subjects = ["Matematicas" , "Biologia", "Quimica", "Fisica"]
    @Maths = File.read('clasifications/Math.json')
    @Schools = File.read('clasifications/Schools.json')
    @material = Material.new
  end

  # GET /materials/1/edit
  def edit
    @subjects = ["Matematicas" , "Biologia", "Quimica", "Fisica"]
    @Maths = File.read('clasifications/Math.json')
    @Schools = File.read('clasifications/Schools.json')
  end

  # POST /materials
  # POST /materials.json
  def create

    @material = Material.new(material_params)
    
    @material.tags = params[:material][:tags]
    @material.schools = params[:material][:schools]
    @material.user_id = current_user.id
    @material.uploadDate = DateTime.now
    # @material.username = current_user.username
    if params[:material][:format] == "file"
      @material.file = params[:material][:file]
      @material.authors = params[:material][:authors]
      if file_type != "unsupported_File"
        @material.file_type = file_type
      end
    else
      set_youtube_data()
    end
    
    if validate_format
      respond_to do |format|
        if @material.save
          format.html { redirect_to @material, notice: 'Material was successfully created.' }
          format.json { render :show, status: :created, location: @material }
        else
          format.html { render :new }
          format.json { render json: @material.errors, status: :unprocessable_entity }
        end
      end  
    end
    
  end

  # PATCH/PUT /materials/1
  # PATCH/PUT /materials/1.json
  def update
    respond_to do |format|
      if @material.update(material_params)
        @material.authors = params[:material][:authors]
        @material.tags = params[:material][:tags]
        @material.updateDate = DateTime.now
        format.html { redirect_to @material, notice: 'Material was successfully updated.' }
        format.json { render :show, status: :ok, location: @material }
      else
        format.html { render :edit }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materials/1
  # DELETE /materials/1.json
  def destroy
    @material.destroy
    respond_to do |format|
      format.html { redirect_to materials_url, notice: 'Material was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.find(params[:id])
    end
    def set_youtube_data
      videoId = youtubeIdFrom(params[:material][:youtube_id])
      video = Yt::Video.new id: videoId
      @material.youtube_id = videoId
      @material.video_duration = video.duration
      # @material.thumbnail_url = video.thumbnail_url
      @material.authors = video.channel_title
      @material.youtubeChannel_id = video.channel_id
      channel = Yt::Channel.new id:  video.channel_id
      @material.youtubeChannel_avatar_url = channel.thumbnail_url
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def material_params

      params.require(:material).permit(:name, :description, :type, :format, :authors, :tags, :subject, :searchable, :schools)
    end
    #Returns the Id of the youtube video url.
    def youtubeIdFrom(url)
      regex = /^.*(?:(?:youtu\.be\/|v\/|vi\/|u\/\w\/|embed\/)|(?:(?:watch)?\?v(?:i)?=|\&v(?:i)?=))([^#\&\?]*).*/
      result = regex.match(url)
      return result[1]
    end
    #Check if it is a supported file type or if it is a video
    def validate_format
      format = params[:material][:format]
      case format
        when "video"
          return true      
        when "file"
          if file_type == "unsupported_File"
            return false
          else
            return true
          end
      else
        return false
      end
    end
    
    #Check MIME Type and returns the type of the file (pdf, excel, slides, etc)
    def file_type
        file = params[:material][:file]
        case file.content_type
            when 'application/pdf'
              return "pdf"           
            when "mage/gif","image/bmp","image/jpeg",'image/png','image/x-icon','image/x-xbitmap'
              return "image"
            when "text/plain"
              return "plain_Text"
            when "application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document","application/vnd.oasis.opendocument.text","application/vnd.sun.xml.writer","application/vnd.sun.xml.writer.global"
              return "text"
            when "application/vnd.openxmlformats-officedocument.presentationml.presentation","application/vnd.ms-powerpoint","application/vnd.ms-powerpoint.presentation.macroenabled.12","application/vnd.sun.xml.impress","application/vnd.sun.xml.impress.template","application/vnd.openxmlformats-officedocument.presentationml.slideshow","application/vnd.ms-powerpoint.presentation.macroenabled.12","application/vnd.oasis.opendocument.presentation","application/vnd.oasis.opendocument.presentation-template"
             return "slides"
            when "application/vnd.ms-excel","application/vnd.ms-excel.sheet.binary.macroenabled.12","application/vnd.ms-excel.sheet.macroenabled.12","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","application/vnd.sun.xml.calc","application/vnd.oasis.opendocument.spreadsheet"
              return "excel"
            when "application/x-rar-compressed","application/x-tar","application/x-7z-compressed","application/zip"
              return "compressed_File"
            when "video/mp4" , "video/ogg" , "video/webm"
              return "uploaded_video"
            
            else
              return "unsupported_File"
        end                
    end 


    
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/materials/_add_to_list.html.erb
<div class="icon plus relative">
	<%if current_user %>
		<div class="add_to_list invisible">
			<div class="triangulo_sup"></div>
			<div class="menu_header">Añadir a:</div>
			<ul class="all_lists">
				<% if current_user.lists.count == 0 %>
					<li><%= "No tienes ninguna lista" %></li>
				<% else %>
				    <% current_user.lists.each do |list| %>
    				    <li list-id="<%= list.id %>" class="relative list_li" ><%= list.name %>
        				    <% if list.materials.include?(params[:id]) %>
        				    	<div class="icon check list_check"></div>
        				    <% else %>
        				    	<div class="icon check-empty list_check"></div>
        				    <% end %>
    				    </li>
				    <% end %>
				<% end %>
			</ul>
			<div class="add_list inactive_form">
				<div class="new_list_form invisible">
					<div class="triangulo_der"></div>
					<%= form_for List.new,:remote => true do |f| %>
					   <%= f.text_field :name, required: true, placeholder: "Nombre"%>
					   <%= f.text_field :description, placeholder: "Descripcion... " %>
					   <%= f.submit "Crear" %>
					<% end %>
				</div>
			</div>
		</div>
	<% else %>
		<div class="add_to_list invisible">
			<div><%= link_to "Iniciar Sesión", new_user_session_path %>	</div>
		</div>
	<% end %>

</div>



<script type="text/javascript">
	$(document).ready(function() {
		var addListButton = $(".add_list");
		var hiddenForm = $(".new_list_form")
		var button = $(".material_actions .icon.plus");
		var invisibleElement = $(".add_to_list");


		$("#new_list").on("ajax:success", function (e, data, status, xhr) {
			var newList = '<li list-id="' + data.id + '" class="relative list_li">' + data.name +'<div class="icon check-empty list_check"></div></li>';
			$(".all_lists").append(newList);
			hiddenForm.addClass("invisible");
			addListButton.removeClass("active_form");
			addListButton.addClass("inactive_form");
			$('input[name="list[description]"]').val("");
			$('input[name="list[name]"]').val("");
		});

		//Add material to list, ajax function and rotating animation
		$(document).delegate( '.list_li', "click", function(){
			$(this).children().addClass("rotating");
			addToList($(this).attr("list-id"));
		});


		var addToList = function (id){
		    $.ajax({
		                 url: "/list/" + "<%= params[:id] %>"+ "/" + id, // Route to favorite
		                type: "GET", // Controller create or destroy method
		            dataType: "json",
		                data: {}, // This goes to Controller in params hash, i.e. params[:file_name]
		            complete: function() {},
		             success: function(data, textStatus, xhr) {
		             		  $("li[list-id=" + id + "] .icon").removeClass("rotating")
		                      $("li[list-id=" + id + "] .icon").toggleClass("check-empty")
		                      $("li[list-id=" + id + "] .icon").toggleClass("check")

		                      },
		               error: function() {
		                        alert("Error al añadir/eleminar de la lista")
		                        // Se añade la clase para poder realizar otra vez la peticion ajax
		                      	$(".favoriteAjax").toggleClass("favoriteAjax")
		          				$(".rotating").removeClass("rotating");
		                      }
		    });
		}


		// Add material to list animation show-hide

		button.on("click", function(){
			if (!button.hasClass("active_button")) {
				setTimeout(function(){
					invisibleElement.removeClass("invisible");			
					button.removeClass("inactive_button")
					button.addClass("active_button");

				},1)
			};
		});
		
		invisibleElement.bind( 'clickoutside', function(event){
			if (button.hasClass("active_button")) {
				
				invisibleElement.addClass("invisible");
				button.removeClass("active_button");
				button.addClass("inactive_form");
			};

		});



		// Create list form animation show-hide 


		addListButton.on("click", function(){
			if (!addListButton.hasClass("active_form")) {
				setTimeout(function(){
					hiddenForm.removeClass("invisible");			
					addListButton.removeClass("inactive_form")
					addListButton.addClass("active_form");

				},1)
			};
		});
		
		hiddenForm.bind( 'clickoutside', function(event){
			if (addListButton.hasClass("active_form")) {
				
				hiddenForm.addClass("invisible");
				addListButton.removeClass("active_form");
				addListButton.addClass("inactive_form");
			};

		});
		
	})
</script>

app/views/materials/_element_info.html.erb
<% if @material.format == "video" %>

app/views/materials/_favorites_script.html.erb
<script type="text/javascript">
// FAVORITES 

<% if user_signed_in? %>
// window.methos helps to now what method use. 
window.method = <% if Favorite.and({ user_id: current_user.id }, { material_id: params[:id] }).count >= 1 %> <%= raw '"DELETE"' %> <% else %><%= raw '"POST"' %><% end %>;


var changeMethod = function () {
	if (window.method == "DELETE") {
		window.method = "POST";
	} else {
		window.method = "DELETE";
	};
}
var updateNumberOfFavs = function(){
	numberOfFavs = parseInt($("number").html())
	if (window.method == "POST") {
		$("number").html(numberOfFavs - 1)
	} else {
		$("number").html(numberOfFavs + 1)
	};
}

var favMaterial = function (method){
	    $.ajax({
	                 url: "<%= material_favorites_path(params[:id]) %>", // Route to favorite
	                type: method, // Controller create or destroy method
	            dataType: "json",
	                data: {}, // This goes to Controller in params hash, i.e. params[:file_name]
	            complete: function() {},
	             success: function(data, textStatus, xhr) {
	                      
	                      // Se añade la clase para poder realizar otra vez la peticion ajax
	                      $(".favs .icon").toggleClass("favoriteAjax")
	    				  // Se queda en amarillo o se quita el amarillo del icono.
	    				  $(".favoriteAjax").toggleClass("active");
	    				  // Se actualiza en pantalla el numero de favoritos que tiene el material
	    				  updateNumberOfFavs();

	                      },
	               error: function() {
	                        alert("Error al añadir/eleminar de favoritos")
	                        // Se añade la clase para poder realizar otra vez la peticion ajax
	                      	$(".favoriteAjax").toggleClass("favoriteAjax")
	                      }
	    });
}

$(document).ready(function(){

	$(document).on("click", '.favoriteAjax', function() {
		// Se quita la clase para evitar mandar otra peticion ajax mientras una esta ya en proceso.
		$(".favoriteAjax").toggleClass("favoriteAjax");
		// Se envía la petición ajax
		favMaterial(window.method);
		// Se cambia el metodo de POST a DELETE o viceversa, para no repetir favoritos,.
	  	changeMethod();
	});
	
	//Al cargar la pagina añadir la clase active si ya esta en favoritos
	if (window.method == "DELETE") {
		$(".favoriteAjax").toggleClass("active");
	};	
});

<% else %>
// En caso de no estar logueado se muestra un mensaje para que inicie sesion
$(document).ready(function(){
	$(document).on("click", '.favoriteAjax', function() {
	 	showBanner();
	});	
})

<% end %>
// END

</script>

app/views/materials/_filter.html.erb
<aside>Filtro

	<%= form_tag '', :method  => :get do |f| %>
	  
	    <%= select_tag(:subject, options_for_select(@subjects), { :include_blank => 'Asignatura ...' })%>
	    <%= select_tag(:type, options_for_select(['Apuntes / Teoría', 'Ejercicios', 'Exámenes', 'Otro']), { :include_blank => 'Tipo...' })%>
	    
	  <%= submit_tag("Aplicar Filtro") %>
	<% end %>

</aside>

app/views/materials/_form.html.erb
<%= form_for(@material) do |f| %>
  <% if @material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@material.errors.count, "error") %> prohibited this material from being saved:</h2>

      <ul>
      <% @material.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field titulo">
    <%= f.text_field :name, placeholder: "Título..." , required: true %>
  </div>
    <div class="field subjectSelector">
    <%= f.select :subject, @subjects, { :include_blank => 'Asignatura ...' }, :required => true %>
        

        <!-- content_tag(:option, "Asignatura...", value: "Asignatura...", :disabled => true, :selected => true)-->    
        
        


  </div>
  <div class="field descripcion">
   
    <%= f.text_area :description, placeholder: "Descripción", required: true  %>
  </div>
  <div class="data">
      <div class="info">
        <div class="field block standarMargin type">
          <%= f.label :type, "¿Qué vas a publicar?" %><br>
          
          <%= f.select(:type) do %>
             
              <%= content_tag(:option, "", value: "", :disabled => true, :selected => true) %>
              
              <% [['Apuntes / Teoría'], ['Ejercicios'], ['Exámenes'],  ['Otro']].each do |c| -%>
                  <%= content_tag(:option, c.first, value: c.last) %>
              <% end %>
          
          <% end %>    
        
        </div>
        
        <div class="field block standarMargin formato">
            <%= f.label :format, "Formato: " %><br>
            
            <%= f.select(:format) do %>
            
                <%= content_tag(:option, "", value: "", :disabled => true, :selected => true) %>
                
                <% [['YouTube Video', 'video'], ['Archivo', 'file']].each do |c| -%>
                  <%= content_tag(:option, c[0], value: c[1]) %>
                <% end %>
            
            <% end %> 
        </div>
      
      </div>

      <div class="info extra">
        
        
        <div class="field block standarMargin searchable">
          <%= f.label :searchable, "¿Quién lo puede ver?" %><br>
          <%= f.select(:searchable) do %>
                <%= content_tag(:option, "", value: "", :disabled => true, :selected => true) %>
                
                <% [['Público', true],["Oculto (No aparecerá en las búsquedas)", false]].each do |c| -%>
                  <%= content_tag(:option, c[0], value: c[1]) %>
                <% end %>
            
          <% end %> 
        </div>
        
        <div class="uploadButton standarMargin">
          <div class="icon cloud-upload uploadIcon"></div>
          <div class="nameOfFile"> Subir Archivo </div>
          <%= f.file_field :file %>
        </div>
       
        <div class="field block standarMargin secundario link">
          <%= f.label :youtube_id %><br>
          <%= f.url_field :youtube_id %>
        </div>
      
      </div>

      <div class="field standarMargin block autor">
          <%= f.label :authors do %>
             Autor/es <low> (Separados por comas)</low> :
          <% end %>
          <br>
          <%= f.text_field :authors , placeholder: "Unicoos, Anónimo, ..." , required: true %>
      </div>

  </div>

  <div class="field clasification block">
    <%= f.label :tags, "Clasificación:" %><br>
    <div class="tags tagName"></div>
    <%= f.hidden_field :tags %>

  </div>

  <div class="field clasification block">
    <%= f.label :schools, "Escuela (Opcional):" %><br>
    <div class="schools tagName"></div>
    <%= f.hidden_field :schools %>
  </div>

  <div class="actions">
    <%= f.submit "¡Listo!" %>
  </div>

<% end %>



<script>
$(document).ready(function () {
  
  String.prototype.capitalize = function() {
    return this.charAt(0).toUpperCase() + this.slice(1);
  }
  
  var resetFile = function(){
    $("input[type='file']").val("");
    $(".nameOfFile").text("Subir Archivo");
    $(".removeIcon").removeClass("removeIcon");
    $(".inputWithFile").removeClass("inputWithFile")
    $(".nameOfFileWithFile").removeClass("nameOfFileWithFile")
    $(".uploadIcon").addClass("cloud-upload");
    $(".uploadIcon").removeClass("remove");
    $(".uploadButton").removeClass("largeUploadButton");
  };
  
  $(document).delegate( '.removeIcon', "click",function(){
    resetFile();
  });
  
  $("input[type='file']").prop('required',true);
  
  $("select").prop('required',true);
  
  $(".uploadMaterial").toggleClass("invisible");
  
  $( ".formato select" ).change(function() {
      var selected = $( ".formato select option:selected" ).text();
      
      $(".secundario").addClass("invisible");
      if (selected == ''){
        $(".secundario").addClass("invisible")
      }else if (selected == 'YouTube Video') {
        $(".link").removeClass("invisible");
        $(".autor input").prop('required',false);
        $(".link label").html("Enlace al vídeo (Youtube):");
        $(".link input").attr("placeholder" , "https://www.youtube.com/watch?v=........");
        //$(".youtubeChannel label").html("Enlace al canal de youtube:");
        //$(".youtubeChannel input").attr("placeholder", "https://www.youtube.com/channel/......");
        resetFile();
        $(".link input").prop('required',true);
        $("input[type='file']").prop('required',false);
        $(".autor , .uploadButton").addClass("invisible")
      }else {
        $(".autor input").prop('required',true);
        $(".link input").prop('required',false);
        $(".autor , .uploadButton").removeClass("invisible");
        $("input[type='file']").prop('required',true);
      }; 
  
  }).trigger("change");
  
  var setClasification = function(){
    window.clasification = [];
    var MathsJSON = <%= raw @Maths %>;
    if ($( ".subjectSelector select option:selected").text() == "Matematicas") {
      window.clasification = MathsJSON;
    };
  };

  var setSchools = function(){
    window.schools = <%= raw @Schools %>;
  }
  
  var update = function(typeOfElement){
    if (typeOfElement == "tags") {
      setClasification();
      $("div[type='tags']").not(".noselected").each(function(){
        window.clasification = window.clasification[$(this).children().text()];
      })
    }else{
      setSchools();
      $("div[type='schools']").not(".noselected").each(function(){
        window.schools = window.schools[$(this).children().text()];
      });
    };
  };

  var showNew = function(typeOfElement){
    var newElements = [];
    var position = "";
    if (typeOfElement == "schools") {
      if (!Array.isArray(window.schools)) {
        $.each(window.schools,function(key , value){newElements.push(key)})
      }else{
        position = "last";
        $.each(window.schools,function(key , value){newElements.push(value)})
      };
    }else{
      if (!Array.isArray(window.clasification)) {
        $.each(window.clasification, function(key , value){newElements.push(key)});
      }else{
        position = "last";
        $.each(window.clasification, function(key , value){newElements.push(value)})
      };
    };
    $.each(newElements, function(key, value){
      $("." + typeOfElement).append('<div class="element '+position+' noselected"  type="' + typeOfElement + '"><div class="tagName">' + value + '</div> +</div>');
    });
  };
  
  var selectElement= function(element){
    typeOfElement = element.attr("type");
    $("div[type="+typeOfElement+"]").not(".noselected").last().toggleClass("index");
    element.toggleClass("selected");
    element.toggleClass("index");
    element.toggleClass("noselected");
    element.html(element.html().replace("+","-"));
    $('div[type='+typeOfElement+']').not(".selected").remove();
    if (!element.hasClass("last")) {
      update(typeOfElement);
      showNew(typeOfElement);
    };
  };
  
  var resetValueOfInput = function(typeOfElement){
    var value = [];
    $('div[type='+typeOfElement+']').not(".noselected").each(function(){
      value.push($(this).children().text());
    });
    $("#material_" + typeOfElement).attr("value",value);
  }

  $(".subjectSelector select").change(function() {
      setClasification();
      $('div[type="tags"]').remove();
      showNew("tags");
  }).trigger("change");
  
  $(document).delegate( '.noselected', "click", function() {
    selectElement($(this));
    resetValueOfInput(typeOfElement);
  });

  $(document).delegate( '.index', "click", function() {
    typeOfElement = $(this).attr("type");
    $(this).remove();
    $('div[type='+typeOfElement+']').not(".selected").remove();
    $('div[type='+typeOfElement+']').last().toggleClass("index");
    update(typeOfElement);
    showNew(typeOfElement);
    resetValueOfInput(typeOfElement);
  });
  
  setSchools();
  
  showNew("schools");
  
  $('input[type=file]').change(function(e){
    var file = $(this).val().split("\\");
    var nameOfFile = file[file.length - 1]
    if (nameOfFile == "") {
      resetFile();
    }else{
      $(".uploadIcon").removeClass("cloud-upload");
      $(".uploadIcon").addClass("remove");
      $(".uploadIcon").addClass("removeIcon")
      $(".nameOfFile").text(nameOfFile);
      $(".nameOfFile").addClass("nameOfFileWithFile");
      $(this).addClass("inputWithFile");
      $(".uploadButton").addClass("largeUploadButton")
    };
  });
  
  $(".showless").on("click",function(){
    $(".centered").toggleClass("invisible");
    $(this).toggleClass("upload-circle");
    $(this).toggleClass("download-circle");
  });

});

  
</script>

app/views/materials/_material.html.erb
           
    <%= link_to material , :class => "thumbnail" do %>
      
        <% if material.format == 'video' %>

            <div class="duration">
                <% if material.video_duration > 3600 %>
                    <%= Time.at(material.video_duration).utc.strftime("%H:%M:%S") %>
                <% else %>
                    <%= Time.at(material.video_duration).utc.strftime("%M:%S") %>
                <% end %>
            </div>

            <%= image_tag("http://i.ytimg.com/vi/" + material.youtube_id + "/mqdefault.jpg", :class => "youtubeThumbnail") %>
        

        <% else %>
             <%= image_tag(material.file_type + ".png", :class => "elementThumbnail") %> 
        <%end %>
    <% end %>
    
    <div class="block1">  
        <%= link_to material do %>
            <div class="related_name">
                <%= material.name %>
            </div>
        <% end %>

       

app/views/materials/_related.html.erb
<div class="related">
	Material relacionado <br><hr>
    <% if Material.where(tags: Regexp.new(@material.tags, true)).ne(id: @material.id).count == 0 %>
        <br>
        No hay material similar
        <br>
    <% end %>
	<% Material.where(tags: Regexp.new(@material.tags, true)).ne(id: @material.id).each do |material| %>
	<div class="recomended_material">
		<%= render partial: "material", locals: {material: material} %>
			 <div class="author">
	            <% material.authors.split(",").each do |author| %>
	              <%= author %>
	            <% end %>
	        </div>
	    </div>
	</div>
	        
	<% end %>
</div>

app/views/materials/edit.html.erb
<article>
<div class="centered">
	<p class="estandarFont topSeparation">A tener en cuenta:</p> 
	<br>
	<ul class="estandarFont">
		<li>
			· <important>Clasifica</important> bien el contenido, así se encuentra mas facil
		</li>
		<br>
		<li>
			· Los <important>derechos de autor</important> son muy importantes, apunta los autores y, si tiene copyright, <attention>no lo publiques </attention>.
		</li>
		<br>
		<li>
		· Lo bueno del contenido multimedia es que <important>si el material tiene un error </important> se puede editar y corregirlo. Especialmente en los videos, si apareciera un error, aunque se advierta dentro del vídeo,<attention> no lo publiques.</attention>
		</li>
	</ul>
</div>
<div class="icon upload-circle showless"></div>
<%= render 'form' %>

</article>

app/views/materials/index.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'search', media: "all"%>
<% end %>
<article class ="materials_index">
<%= render 'filter' %>
  <div class="materials">




    <% @materials.each do |material| %>
        <div class="material">
          <%= render partial: "material", locals: {material: material} %>
            <div class="description">
              <% material.authors.split(",").each do |author| %>
                <%= author + ". "%>
              <% end %>
              <br>
              <%= material.description %>
            </div>
          </div>
        </div>
    <% end %>

  <br>


  </div>
</article>

<script type="text/javascript">
  var youtubeVideoIdRegEx = /^.*(?:(?:youtu\.be\/|v\/|vi\/|u\/\w\/|embed\/)|(?:(?:watch)?\?v(?:i)?=|\&v(?:i)?=))([^#\&\?]*).*/;
  function videoId (youtubeUrl) {
    return youtubeUrl.match(youtubeVideoIdRegEx)[1];  
  }
  //$(document).ready(function(){
   // $(".youtubeThumbnail").each(function(){
    //  $(this).attr("src" ,"http://i.ytimg.com/vi_webp/" + videoId($(this).attr("src")) + "/mqdefault.webp");
    //})

  //});
</script>

app/views/materials/new.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'materials_form', media: "all"%>
<% end %>
<article>
<div class="centered">
	<p class="estandarFont topSeparation">A tener en cuenta:</p> 
	<br>
	<ul class="estandarFont">
		<li>
			· <important>Clasifica</important> bien el contenido, así se encuentra más fácil
		</li>
		<br>
		<li>
			· Los <important>derechos de autor</important> son muy importantes. Indica los autores y, si tiene copyright, <attention>no lo publiques </attention>.
		</li>
		<br>
		<li>
		· Lo bueno del contenido multimedia es que <important>si el material presenta un error </important> se puede editar y ser corregido. No obstante en los vídeos, si apareciera un error, aunque se advierta dentro del vídeo,<attention> no lo publiques.</attention>
		</li>
	</ul>
</div>
<div class="icon upload-circle showless"></div>
<%= render 'form' %>

</article>